### ISSUE TITLE
Can't set up adblocking

### ISSUE THREAD

**Issue by thoth-amon** [LeFroid/Viper-Browser#20] opened 2021-02-12 16:01 UTC
0.91 Appimage

When I do the initial setup, I select the checkboxes but the Finish button does not work. I can't add them to list from the manage ad blocker screen either.

**Comment by LeFroid** [comment] 2021-02-13 16:05
Can you please share the following information?

- Host operating system
- Qt version
- Qt WebEngine version (if different than base Qt version)
- Host Arch - x86, ARM, etc

And have you tried selecting any subscriptions from the recommended list, as in this screenshot?
![image](https://user-images.githubusercontent.com/2191538/107854663-71dd4200-6deb-11eb-9d29-ce7cfebb211d.png)

**Comment by thoth-amon** [comment] 2021-02-13 20:39
Kubuntu 20.04
Qt version 5.12.8 (same for qtwebengine)
x86_64

Yes, I tried from that screen, clicked ok and nothing is added to the list in the background.

**Comment by Nesaijn** [comment] 2021-02-21 08:57
I encountered the same problem with the latest AppImage.
At the beginning tour I couldn't click "Finish" after selecting the preferred subscriptions even selecting none didn't help.
After clicking cancel and trying to subscribe to them after nothing changed when confirming the choice. The window to select the subscriptions  closed but the list kept being empty.

Viper-Browser Version 0.9.1
Qt Version 5.12.0
Qt WebEngine Version can't tell. Installed is qt5-webengine 5.15.2-5 but I have also qt5-base 5.15.2-2 installed which is not used by Viper-Browser.
On Manjaro x86_64

**Comment by LeFroid** [comment] 2021-02-21 19:25
Can you please check for the presence of these folders and files?

- Directory: ~/.config/Vaccarelli/AdBlockPlus 
- File: ~/.config/Vaccarelli/adblock_plus.json

If the folder `AdBlockPlus` is present, do you see any files stored in it? And if `adblock_plus.json` is present, please share the file contents.

**Comment by thoth-amon** [comment] 2021-02-22 00:06
In the adblock plus folder, there is another folder called resources. This is empty.

The content of adblock_plus.json is 

> {
>     "requests_blocked": "0"
> }

**Comment by Nesaijn** [comment] 2021-02-22 20:22
```
$ ls -lAR .config/Vaccarelli/
.config/Vaccarelli/:
total 84
drwxr-xr-x 3 nesaijn nesaijn  4096 21. Feb 09:42 AdBlockPlus
-rw-r--r-- 1 nesaijn nesaijn    32 21. Feb 09:58 adblock_plus.json
-rw-r--r-- 1 nesaijn nesaijn  2048 21. Feb 09:58 bookmarks.db
-rw-r--r-- 1 nesaijn nesaijn  3072 21. Feb 09:58 extension_storage.db
-rw-r--r-- 1 nesaijn nesaijn 15360 21. Feb 09:58 favicons.db
-rw-r--r-- 1 nesaijn nesaijn    76 21. Feb 09:58 favorite_pages.json
-rw-r--r-- 1 nesaijn nesaijn 15360 21. Feb 09:58 history.db
-rw-r--r-- 1 nesaijn nesaijn  3640 21. Feb 09:58 last_session.json
-rw-r--r-- 1 nesaijn nesaijn     4 21. Feb 09:58 user_agents.json
drwxr-xr-x 3 nesaijn nesaijn  4096 21. Feb 09:42 UserScripts
-rw-r--r-- 1 nesaijn nesaijn     4 21. Feb 09:58 user_scripts.json
-rw-r--r-- 1 nesaijn nesaijn  1278 21. Feb 09:43 Viper-Browser.conf
-rw-r--r-- 1 nesaijn nesaijn  9216 21. Feb 09:58 web_thumbnails.db

.config/Vaccarelli/AdBlockPlus:
total 4
drwxr-xr-x 2 nesaijn nesaijn 4096 21. Feb 09:42 resources

.config/Vaccarelli/AdBlockPlus/resources:
total 0

.config/Vaccarelli/UserScripts:
total 4
drwxr-xr-x 2 nesaijn nesaijn 4096 21. Feb 09:42 Dependencies

.config/Vaccarelli/UserScripts/Dependencies:
total 0

$ cat .config/Vaccarelli/adblock_plus.json
{
    "requests_blocked": "0"
}
```

**Comment by LeFroid** [comment] 2021-02-23 03:30
Thank you for sharing this information. I think I've narrowed down the issue to some legacy networking code, and will be testing a fix in the coming days. Will update you both when confident in the remedy.

**Comment by LeFroid** [comment] 2021-02-23 18:29
The adblocking setup is working for me as of the last commit, on a fresh Kubuntu 20.04 VM. The welcome wizard also closes after clicking on the finish button.
Please let me know if you still have any issues subscribing to the filter lists - they can be installed from the Tools -> Manage Ad Blocker window, or the welcome wizard on a fresh install.

**Comment by Nesaijn** [comment] 2021-02-24 21:34
I have used the AppImage from the Continuous build and the the welcome wizard could be finished. When going to manage Ad Blocker the list of selected ad blockers is empty. Selecting them afterwards also does not work. I could manage to at a custom filter entry though. But selecting subscriptions by selecting from list does still not work.

**Comment by LeFroid** [comment] 2021-02-24 23:54
Acknowledged - I’ll debug the AppImage and update when I have more information. Should have something in the next day or two.

**Comment by LeFroid** [comment] 2021-02-25 15:01
The issue seemed to be caused by the outdated build environment in our CI; the Qt packager disabled certain network capabilities because of the very outdated OpenSSL library.
I’ve updated the environment to the latest LTS, and the latest AppImage is now working for me on a clean VM.

I did notice that the welcome window appears for the first two launches instead of only once, but this can be ignored until a fix is in place. All settings and subscriptions are saved after the first launch.

Please let me know if you still have any issues with the AppImage.

**Comment by Nesaijn** [comment] 2021-02-25 15:06
Yes, I can confirm that the problem of adding ad blocking lists works now.
Awesome! Thank you for your work!

**Comment by LeFroid** [comment] 2021-02-25 23:11
Great to hear! Thank you

**Closed by LeFroid** 2021-02-25 23:11 UTC
